config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
      sessions: "admin/sessions"
    }

  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]

    get "dashboards", to: "dashboards#index"
    resources :users, only: [] do
      member do
        patch :withdraw
      end
      resources :posts, only: [:index], controller: "users/posts"
    end
  end

  scope module: :public do
    root to: "homes#top"

    # devise_for :admin, skip: [:registrations, :password], controllers: {
    #   sessions: 'admin/sessions'
    # }

    # namespace :admin do
    #   resources :genres, only: [:create, :index, :edit, :update]
    #   get 'dashboards', to: 'dashboards#index'
    #   resources :users, only: [:destroy]
    # end

    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
    get "home/about", to: "homes#about", as: "about"

    resources :users, only: [:show, :index, :edit, :update] do
      patch "withdraw", on: :member, as: "withdraw_user"
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end

    resources :posts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :edit, :update, :destroy]
    end

    get "search" => "searches#search"
    patch "withdraw/:id" => "users#withdraw", as: "withdraw_user"
    put "withdraw/:id" => "users#withdraw"
  end

  resources :notifications, only: [:update]
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  belongs_to :genre
  has_many :post_comments, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy


  validates :image, attached: true, content_type: ["image/png", "image/jpeg"]
  validates :title, presence: true
  validates :body, presence: true


  def get_image
    if image.attached?
      image
    else
      "no_image.jpg"
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @post = Post.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @post = Post.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?", "%#{word}%")
    else
      @post = Post.all
    end
  end

  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_post, only: [:destroy]

  def index
    @posts = Post.includes(:post_comments)
    if params[:post_id].present?
      @posts = @posts.where(id: params[:post_id])
    else
      @posts = @posts.where("title LIKE ?", "%#{params[:keyword]}%").or(
                 @posts.where("body LIKE ?", "%#{params[:keyword]}%")) if params[:keyword].present?
      @posts = @posts.where(genre_id: params[:genre_id]) if params[:genre_id].present?
    end
    @posts = @posts.page(params[:page]).per(5)
  end

  def destroy
    @post.destroy
    flash[:notice] = "Deteled Post."
    redirect_to admin_posts_path
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_genre, only: [:index, :new, :edit, :create, :update]
  
  def new
    @post = Post.new
  end
  
  def create
    #byebug
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = 'Successfully shared.'
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def index
    @post = Post.all
  end

  def show
     @post = Post.find(params[:id])
     @post_comment = PostComment.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
      if @post.update(post_params)
        flash[:notice] = 'Successfully Updated.'
        redirect_to post_path(@post.id)  
      else
        render :edit
      end 
  end
  
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end
  
  private
    def set_post
      @post = Post.find(params[:id])
    end

    def set_genre
      @genres = Genre.all
    end
  

    def post_params
      params.require(:post).permit(:image, :genre_id, :title, :body)
    end
  
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <%= form_with url: admin_posts_path, method: :get do |f| %>
        <div class="row">
          <div class="col-sm-6 mb-2">
            <%= f.search_field :keyword, placeholder: "キーワードで検索", value: params[:keyword], class: "form-control" %>
          </div>
          <div class="col-sm-4 mb-2">
            <%= f.collection_select :genre_id, Genre.all, :id, :name, { include_blank: "-genre select-", selected: params[:genre_id]}, { class: "form-control" } %>
          </div>
          <div class="col-sm-2 mb-2">
            <%= f.submit "検索", class: "btn btn-primary btn-block" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center">All Posts</h1>
      <table class="table table-bordered table-borderless">
        <% @posts.each do |post| %>
          <tr>
            <th class="col-3">User name</th>
            <td class="col-9"><%= link_to post.user.name, admin_dashboards_path(user_id: post.user.id) %></td>
          </tr>
          <tr>
            <th class="col-3">Image</th>
            <td class="col-9"><%= link_to admin_post_comments_path(post) do %>
              <%= image_tag post.get_image, class: "img-fluid" %>
            <% end %></td>
          </tr>
          <tr>
            <th class="col-3">Genre</th>
            <td class="col-9"><%= post.genre.name if post.genre.present? %></td>
          </tr>
          <tr>
            <th class="col-3">Title</th>
            <td class="col-9"><%= post.title %></td>
          </tr>
          <tr>
            <th class="col-3">Caption</th>
            <td class="col-9"><%= post.body %></td>
          </tr>
          <tr>
            <th class="col-3">削除ボタン</th>
            <td class="col-9">
              <%= link_to "Delete this post as an Administrator", admin_post_path(post), method: :delete, class: "btn btn-danger btn-block" %>
            </td>
          </tr>
          <!-- レビュー評価 -->
          <tr>
            <td colspan="2" class="text-center">
              <div id="star-rate<%= post.id %>"></div>
              <script>
                $('#star-rate<%= post.id %>').empty();
                $('#star-rate<%= post.id %>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  half      : false,
                  readOnly  : true,
                  score     : <%= post.post_comments.average(:star).to_f %>,
                });
              </script>
            </td>
          </tr>
          <!-- 投稿ごとのスペース -->
          <tr><td colspan="2">&nbsp;</td></tr>
        <% end %>
      </table>

      <div class="row justify-content-center">
        <%= paginate @posts %>
      </div>

    </div>
  </div>
</div>