config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
      sessions: "admin/sessions"
    }

  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]

    get "dashboards", to: "dashboards#index"
    resources :users, only: [] do
      member do
        patch :withdraw
      end
      resources :posts, only: [:index], controller: "users/posts"
    end
  end

  scope module: :public do
    root to: "homes#top"

    # devise_for :admin, skip: [:registrations, :password], controllers: {
    #   sessions: 'admin/sessions'
    # }

    # namespace :admin do
    #   resources :genres, only: [:create, :index, :edit, :update]
    #   get 'dashboards', to: 'dashboards#index'
    #   resources :users, only: [:destroy]
    # end

    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
    get "home/about", to: "homes#about", as: "about"

    resources :users, only: [:show, :index, :edit, :update] do
      patch "withdraw", on: :member, as: "withdraw_user"
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end

    resources :posts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :edit, :update, :destroy]
    end

    get "search" => "searches#search"
    patch "withdraw/:id" => "users#withdraw", as: "withdraw_user"
    put "withdraw/:id" => "users#withdraw"
  end

  resources :notifications, only: [:update]
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :comment, presence: true
  validates :star, presence: true
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :set_post, only: [:destroy]
  before_action :set_post_comment, only: [:destroy]

  def index
    @post_comments = PostComment.all
    @post_comments = @post_comments.where("comment LIKE ?", "%#{params[:keyword]}%") if params[:keyword].present?

    @post_comments = @post_comments.page(params[:page])
  end

  def destroy
    @post_comment.destroy
    redirect_to admin_post_post_comments_path(post_id: @post.id), notice: "Comment was deleted."
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_post_comment
      @post_comment = PostComment.find(params[:id])
    end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/admin/post_comments/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <%= form_with url: admin_post_comments_path, method: :get do |f| %>
        <div class="row">
          <div class="col-sm-9 mb-2">
            <%= f.search_field :keyword, placeholder: "キーワードで検索", value: params[:keyword], class: "form-control" %>
          </div>
          <div class="col-sm-3 mb-2">
            <%= f.submit "検索", class: "btn btn-primary btn-block" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1 class="text-center">All Posts</h1>
      <table class="table table-bordered table-borderless">
        <% @post_comments.each do |post_comment| %>
          <tr>
            <th class="col-3">User name</th>
            <td class="col-9"><%= link_to post_comment.user.name, admin_dashboards_path(user_id: post_comment.user.id) %></td>
          </tr>
          <tr>
            <th class="col-3">Image</th>
            <td class="col-12">
              <%= link_to admin_posts_path(post_id: post_comment.post.id) do %>
                <%= image_tag post_comment.post.get_image %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th class="col-3">Comments</th>
            <td class="col-9"><%= post_comment.comment %></td>
          </tr>

          <tr>
            <th class="col-3">削除ボタン</th>
            <td class="col-9">
              <%= link_to "Delete this post as an Administrator", admin_post_comment_path(post_comment), method: :delete, class: "btn btn-danger btn-block" %>
            </td>
          </tr>
        <% end %>
      </table>

      <div class="row justify-content-center">
        <%= paginate @post_comments %>
      </div>

    </div>
  </div>
</div>