config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
      sessions: "admin/sessions"
    }

  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]

    get "dashboards", to: "dashboards#index"
    resources :users, only: [] do
      member do
        patch :withdraw
      end
      resources :posts, only: [:index], controller: "users/posts"
    end
  end

  scope module: :public do
    root to: "homes#top"

    # devise_for :admin, skip: [:registrations, :password], controllers: {
    #   sessions: 'admin/sessions'
    # }

    # namespace :admin do
    #   resources :genres, only: [:create, :index, :edit, :update]
    #   get 'dashboards', to: 'dashboards#index'
    #   resources :users, only: [:destroy]
    # end

    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
    get "home/about", to: "homes#about", as: "about"

    resources :users, only: [:show, :index, :edit, :update] do
      patch "withdraw", on: :member, as: "withdraw_user"
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end

    resources :posts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :edit, :update, :destroy]
    end

    get "search" => "searches#search"
    patch "withdraw/:id" => "users#withdraw", as: "withdraw_user"
    put "withdraw/:id" => "users#withdraw"
  end

  resources :notifications, only: [:update]
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
    if params[:keyword].present?
      @users = @users.where("name LIKE ?", "%#{params[:keyword]}%").or(
               @users.where("email LIKE ?", "%#{params[:keyword]}%"))
    elsif params[:user_id].present?
      @users = @users.where(id: params[:user_id])
    end
  end
end

app/helpers/admin/dashboards_helper.rb
module Admin::DashboardsHelper
end

app/views/admin/dashboards/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <%= form_with url: admin_dashboards_path, method: :get do |f| %>
        <div class="row">
          <div class="col-sm-9 mb-2">
            <%= f.search_field :keyword, placeholder: "search keywords", value: params[:keyword], class: "form-control" %>
          </div>
          <div class="col-sm-3 mb-2">
            <%= f.submit "Search", class: "btn btn-primary btn-block" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h3 class="text-center">Users List</h3>
      <ul class="list-group mb-4"> 
        <% @users.each do |user| %>
          <li class="list-group-item d-flex justify-content-between align-items-center" style="<%= 'background-color: gray' unless user.is_valid %>">
            <div>
              <strong><%= user.name %></strong> - <%= user.email %>
            </div>
            <div>
              <% unless user.is_valid %>
                <span>User left</span>
              <% else %>
                <%= link_to 'Delete', withdraw_admin_user_path(user), method: :patch, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure you want to delete this user?' } %>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
      <div class="text-center">
        <%= link_to "Back", admin_genres_path, class: "btn btn-primary btn-block" %> 
      </div>
    </div>
  </div>
</div>