config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
      sessions: "admin/sessions"
    }

  namespace :admin do
    resources :genres, only: [:create, :index, :edit, :update, :destroy]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]

    get "dashboards", to: "dashboards#index"
    resources :users, only: [] do
      member do
        patch :withdraw
      end
      resources :posts, only: [:index], controller: "users/posts"
    end
  end

  scope module: :public do
    root to: "homes#top"

    # devise_for :admin, skip: [:registrations, :password], controllers: {
    #   sessions: 'admin/sessions'
    # }

    # namespace :admin do
    #   resources :genres, only: [:create, :index, :edit, :update]
    #   get 'dashboards', to: 'dashboards#index'
    #   resources :users, only: [:destroy]
    # end

    devise_for :users, controllers: {
      registrations: "public/registrations",
      sessions: "public/sessions"
    }
    get "home/about", to: "homes#about", as: "about"

    resources :users, only: [:show, :index, :edit, :update] do
      patch "withdraw", on: :member, as: "withdraw_user"
      resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
      get "followers" => "relationships#followers", as: "followers"
    end

    devise_scope :user do
      post "users/guest_sign_in", to: "sessions#guest_sign_in"
    end

    resources :posts, only: [:new, :create, :show, :index, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :edit, :update, :destroy]
    end

    get "search" => "searches#search"
    patch "withdraw/:id" => "users#withdraw", as: "withdraw_user"
    put "withdraw/:id" => "users#withdraw"
  end

  resources :notifications, only: [:update]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Parati</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/70b5054063.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light nav-custom">
        <div class="container-fluid">
          <div class="col-1"></div>
          <% if user_signed_in? %>
            <% link_path = posts_path %>
          <% elsif admin_signed_in? %>
            <% link_path = admin_genres_path %>
          <% else %>
            <% link_path = new_user_session_path %>
          <% end %>
          <a class="navbar-brand font-weight-bold" href="<%= link_path %>">ParaTi</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? && !user_signed_in? %>
               <li>
                <%= link_to admin_post_comments_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i> Post Comments
                <% end %>
               </li>

               <li>
                <%= link_to admin_posts_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i> Posts
                <% end %>
               </li>

               <li>
                <%= link_to admin_dashboards_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-users"></i> Users
                <% end %>
               </li>

               <li>
                <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
               </li> 

              <% elsif user_signed_in? %>
                <li class="nav-item">
                  <div class="search_form">
                    <%= form_with url: search_path, local: true, method: :get, class: "form-inline mr-2" do |f| %>
                      <%= f.collection_select :word, Genre.all, :name, :name, { prompt: "Choose Genre" }, { class: "form-control mr-1" } %>
                      <%= f.hidden_field :range, value: 'Genre' %>
                      <%= f.hidden_field :search, value: "partial_match" %>
                      <%= f.submit "Search", class: "btn btn-white" %>
                    <% end %>
                  </div>
                </li>

                <li class="nav-item">
                  <div class="search_form">
                    <%= form_with url: search_path, local: true, method: :get, class: "form-inline" do |f| %>
                      <%= f.text_field :word, placeholder: "Search keyword", class: "form-control mr-1" %>
                      <%= f.select :range, options_for_select([['User'], ['Post']]), {}, { class: "form-control mr-1" } %>
                      <%= f.hidden_field :search, value: "partial_match" %>
                      <%= f.submit "Search", class: "btn btn-white" %>
                    <% end %>
                  </div>
                </li>
                
                <li class="nav-item">
                  <%= link_to posts_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home"></i> Home
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-user"></i> MyPage
                  <% end %>
                </li>
                
                <li class="nav-item">
                  <%= link_to new_post_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-square-plus"></i> Post
                  <% end %>
                </li>

                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              
                <li class="dropdown">
                  <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color: transparent; border: none; color: #fff;">
                    Notification
                    <span class="badge badge-danger"><%= current_user.notifications.where(read: false).count %></span>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <% if current_user.notifications.where(read: false).any? %>
                      <small class="dropdown-item disabled">Showing the last 5 unread notifications</small>
                      <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                        <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                      <% end %>
                    <% else %>
                      <span class="dropdown-item disabled">No unread notifications</span>
                    <% end %>
                  </div>
                </li>
              <% else %>
            
                <li class="nav-item">
                  <%= link_to "/", class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-home"></i> Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-link"></i> About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fa-solid fa-user-plus"></i> Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              
              <% end %>
            </ul>
          </div>
          <div class="col-1"></div>
        </div>
      </nav>
    </header>
  </body>
    <main>
  <div class="container mt-4">
      <div class="row">
        <div class="col-md-8 mx-auto">
          <% if flash[:notice] %>
            <div class="alert alert-success">
              <%= flash[:notice] %>
            </div>
          <% end %>
          <% if flash[:alert] %>
            <div class="alert alert-danger">
              <%= flash[:alert] %>
            </div>
          <% end %>
        </div>
          <%= yield %>
      </div>
    </div>
    </main>
  <footer>
    <div class="container mt-5">
    	<div class="row">
      	<div class="mx-auto">
      		<p>CopyRight ParaTi.inc</p>
      	</div>
      </div>
    </div>
  </footer>

</html>